# Generated by Django 3.0.3 on 2020-02-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_visitedpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitedpost',
            old_name='visited',
            new_name='visited_on',
        ),
        migrations.AddField(
            model_name='visitedpost',
            name='post_id',
            field=models.CharField(default='N/A', max_length=30),
        ),
    ]
